# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 850)
        MainWindow.setMinimumSize(QtCore.QSize(900, 850))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.imgLabel = QtWidgets.QLabel(self.centralwidget)
        self.imgLabel.setText("")
        self.imgLabel.setObjectName("imgLabel")
        self.verticalLayout_6.addWidget(self.imgLabel)
        self.editorWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editorWidget.sizePolicy().hasHeightForWidth())
        self.editorWidget.setSizePolicy(sizePolicy)
        self.editorWidget.setMinimumSize(QtCore.QSize(150, 150))
        self.editorWidget.setMaximumSize(QtCore.QSize(16777215, 260))
        self.editorWidget.setObjectName("editorWidget")
        self.gist_wdg = QtWidgets.QWidget()
        self.gist_wdg.setObjectName("gist_wdg")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.gist_wdg)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 831, 231))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.all_gist = PlotWidget(self.horizontalLayoutWidget)
        self.all_gist.setObjectName("all_gist")
        self.horizontalLayout.addWidget(self.all_gist)
        self.red_gist = PlotWidget(self.horizontalLayoutWidget)
        self.red_gist.setObjectName("red_gist")
        self.horizontalLayout.addWidget(self.red_gist)
        self.blue_gist = PlotWidget(self.horizontalLayoutWidget)
        self.blue_gist.setObjectName("blue_gist")
        self.horizontalLayout.addWidget(self.blue_gist)
        self.green_gist = PlotWidget(self.horizontalLayoutWidget)
        self.green_gist.setObjectName("green_gist")
        self.horizontalLayout.addWidget(self.green_gist)
        self.editorWidget.addTab(self.gist_wdg, "")
        self.rgb_wdg = QtWidgets.QWidget()
        self.rgb_wdg.setObjectName("rgb_wdg")
        self.red_sld = QtWidgets.QSlider(self.rgb_wdg)
        self.red_sld.setGeometry(QtCore.QRect(150, 30, 641, 31))
        self.red_sld.setMinimum(-255)
        self.red_sld.setMaximum(255)
        self.red_sld.setOrientation(QtCore.Qt.Horizontal)
        self.red_sld.setObjectName("red_sld")
        self.green_sld = QtWidgets.QSlider(self.rgb_wdg)
        self.green_sld.setGeometry(QtCore.QRect(150, 80, 641, 31))
        self.green_sld.setMinimum(-255)
        self.green_sld.setMaximum(255)
        self.green_sld.setOrientation(QtCore.Qt.Horizontal)
        self.green_sld.setObjectName("green_sld")
        self.blue_sld = QtWidgets.QSlider(self.rgb_wdg)
        self.blue_sld.setGeometry(QtCore.QRect(150, 130, 641, 31))
        self.blue_sld.setMinimum(-255)
        self.blue_sld.setMaximum(255)
        self.blue_sld.setOrientation(QtCore.Qt.Horizontal)
        self.blue_sld.setObjectName("blue_sld")
        self.label_4 = QtWidgets.QLabel(self.rgb_wdg)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 121, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.rgb_wdg)
        self.label_5.setGeometry(QtCore.QRect(10, 80, 121, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.rgb_wdg)
        self.label_6.setGeometry(QtCore.QRect(10, 130, 121, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.editorWidget.addTab(self.rgb_wdg, "")
        self.resize_wdj = QtWidgets.QWidget()
        self.resize_wdj.setObjectName("resize_wdj")
        self.width_edit = QtWidgets.QLineEdit(self.resize_wdj)
        self.width_edit.setGeometry(QtCore.QRect(380, 60, 121, 31))
        self.width_edit.setObjectName("width_edit")
        self.height_edit = QtWidgets.QLineEdit(self.resize_wdj)
        self.height_edit.setGeometry(QtCore.QRect(380, 110, 121, 31))
        self.height_edit.setObjectName("height_edit")
        self.label_7 = QtWidgets.QLabel(self.resize_wdj)
        self.label_7.setGeometry(QtCore.QRect(210, 60, 121, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.resize_wdj)
        self.label_8.setGeometry(QtCore.QRect(210, 110, 121, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.editorWidget.addTab(self.resize_wdj, "")
        self.edit_wdg = QtWidgets.QWidget()
        self.edit_wdg.setObjectName("edit_wdg")
        self.brightness_sld = QtWidgets.QSlider(self.edit_wdg)
        self.brightness_sld.setGeometry(QtCore.QRect(150, 80, 641, 31))
        self.brightness_sld.setMinimum(-100)
        self.brightness_sld.setMaximum(100)
        self.brightness_sld.setOrientation(QtCore.Qt.Horizontal)
        self.brightness_sld.setObjectName("brightness_sld")
        self.contrast_sld = QtWidgets.QSlider(self.edit_wdg)
        self.contrast_sld.setGeometry(QtCore.QRect(150, 130, 641, 31))
        self.contrast_sld.setMinimum(-100)
        self.contrast_sld.setMaximum(100)
        self.contrast_sld.setSingleStep(10)
        self.contrast_sld.setPageStep(10)
        self.contrast_sld.setOrientation(QtCore.Qt.Horizontal)
        self.contrast_sld.setObjectName("contrast_sld")
        self.label_2 = QtWidgets.QLabel(self.edit_wdg)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 121, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.edit_wdg)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 131, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.editorWidget.addTab(self.edit_wdg, "")
        self.verticalLayout_6.addWidget(self.editorWidget)
        self.reset_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset_btn.sizePolicy().hasHeightForWidth())
        self.reset_btn.setSizePolicy(sizePolicy)
        self.reset_btn.setMinimumSize(QtCore.QSize(1, 0))
        self.reset_btn.setObjectName("reset_btn")
        self.verticalLayout_6.addWidget(self.reset_btn)
        self.saveBtn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveBtn.sizePolicy().hasHeightForWidth())
        self.saveBtn.setSizePolicy(sizePolicy)
        self.saveBtn.setObjectName("saveBtn")
        self.verticalLayout_6.addWidget(self.saveBtn)
        self.uploadBtn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uploadBtn.sizePolicy().hasHeightForWidth())
        self.uploadBtn.setSizePolicy(sizePolicy)
        self.uploadBtn.setMinimumSize(QtCore.QSize(1, 0))
        self.uploadBtn.setObjectName("uploadBtn")
        self.verticalLayout_6.addWidget(self.uploadBtn)
        self.editorWidget.raise_()
        self.imgLabel.raise_()
        self.uploadBtn.raise_()
        self.reset_btn.raise_()
        self.saveBtn.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.editorWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.editorWidget.setTabText(self.editorWidget.indexOf(self.gist_wdg), _translate("MainWindow", "Гистограмма"))
        self.label_4.setText(_translate("MainWindow", "RED"))
        self.label_5.setText(_translate("MainWindow", "GREEN"))
        self.label_6.setText(_translate("MainWindow", "BLUE"))
        self.editorWidget.setTabText(self.editorWidget.indexOf(self.rgb_wdg), _translate("MainWindow", "RGB"))
        self.label_7.setText(_translate("MainWindow", "Ширина"))
        self.label_8.setText(_translate("MainWindow", "Высота"))
        self.editorWidget.setTabText(self.editorWidget.indexOf(self.resize_wdj), _translate("MainWindow", "Page"))
        self.label_2.setText(_translate("MainWindow", "Яркость"))
        self.label_3.setText(_translate("MainWindow", "Констрастность"))
        self.editorWidget.setTabText(self.editorWidget.indexOf(self.edit_wdg), _translate("MainWindow", "Редактировать"))
        self.reset_btn.setText(_translate("MainWindow", "Отмена"))
        self.saveBtn.setText(_translate("MainWindow", "Сохранить"))
        self.uploadBtn.setText(_translate("MainWindow", "Загрузить"))
from pyqtgraph import PlotWidget
